DROP TABLE IF EXISTS Kansliga_uppgifter CASCADE;
DROP TABLE IF EXISTS Konsult CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS Klass CASCADE;
DROP TABLE IF EXISTS Kurs CASCADE;
DROP TABLE IF EXISTS Utbildningsledare CASCADE;
DROP TABLE IF EXISTS Program CASCADE;